# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Dockerfile used to run the tests independently of your local go setup

FROM golang:1.16-buster

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
      curl \
      gcc \
      git \
  && git config --global user.name "John Doe" \
  && git config --global user.email "john.doe@example.com"
 
ADD go.mod .
ADD go.sum .
RUN go mod download

ADD . .

RUN go test ./... -covermode=count -coverprofile=coverage.out
